### ISSUE TITLE
Feature: Prefix commands

### ISSUE THREAD

**Issue by jharvey-galco** [Mirasaki/discord.js-bot-template#102]
**Is your feature request related to a problem? Please describe.**
Not Related to any Problem

**Describe the solution you'd like**
Support for Prefix Commands

**Comment by Mirasaki** [comment]
Hey there!

Yes, we can add support for prefix commands. I'll be doing some development on the project tomorrow and will see if I can fit it in!

Any specific things you'd like to point out for this feature request?

**Comment by Mirasaki** [comment]
Actually, I'm honestly not sure if we should. The primary point I make in the description is that using prefix commands is the old way of doing things and should be considered deprecated as far as Discord is concerned. Maybe if this issue gets more traffic in the future we can revisit the topic - for now, I'll be closing this.
