### ISSUE TITLE
[BUG] - [09:04:47] [SYSERR] : Missing interaction listener for "info" (name for commands, customId for components - ignored if starts with "@")

### ISSUE THREAD

**Issue by axueikawa** [Mirasaki/discord.js-bot-template#142]
[09:04:47] [SYSERR] : Missing interaction listener for "info" (name for commands, customId for components - ignored if starts with "@")

**Comment by Mirasaki** [comment]
If you believe this is a bug, provide a minimal reproducible example and your version from the package.json

**Comment by Mirasaki** [comment]
I do have to update the documentation for this though.
